/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AmbulanceRole;

import Business.Country.Country;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.ReceptionistOrganization;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Person.VitalSign;
import Business.SMS.sms;
import Business.State.State;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.IncidentWorkRequest;
import Business.WorkQueue.VehicleWorkRequest;
import com.twilio.sdk.TwilioRestException;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author raunak
 */
public class RequestIncidentJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Person p;
    private Country country;
    private State state;
    private EcoSystem ecosystem;
    private VehicleWorkRequest vworkrq;

    //  private AmbulanceOrganization organization;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestIncidentJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Person p, UserAccount account, Enterprise enterprise, VehicleWorkRequest vreq) {
        initComponents();

        //System.out.println(ecosystem.getName());
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.p = p;
        this.vworkrq = vreq;
        this.ecosystem=ecosystem;
      
        for (Country co : ecosystem.getCountryList().getCountryDirectory()) {
            for (State s : co.getStateList().getStateDirectory()) {
                for (UserAccount ua : s.getUserAccountDirectory().getUserAccountList()) {
                    if (ua.getUsername().equals(account.getUsername())) {
                        country = co;
                       
                    }
                     state = s;
                        System.out.println("State name: " + state.getName());
                }
            }
             
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        txtrespRate = new javax.swing.JTextField();
        lblrespRate = new javax.swing.JLabel();
        txtheartRate = new javax.swing.JTextField();
        lblheartRate = new javax.swing.JLabel();
        txtsysBP = new javax.swing.JTextField();
        lblsysBP = new javax.swing.JLabel();
        txtwt = new javax.swing.JTextField();
        lblwt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        requestTestJButton.setText("Request Test");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("ZipCode");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        messageJTextField.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        messageJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageJTextFieldActionPerformed(evt);
            }
        });
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 110, -1));

        backJButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        valueLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 80, -1));

        enterpriseLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, 30));

        txtrespRate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtrespRate.setEnabled(false);
        txtrespRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrespRateActionPerformed(evt);
            }
        });
        add(txtrespRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 110, -1));

        lblrespRate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblrespRate.setText("Respiratory Rate");
        add(lblrespRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtheartRate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtheartRate.setEnabled(false);
        txtheartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtheartRateActionPerformed(evt);
            }
        });
        add(txtheartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 110, -1));

        lblheartRate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblheartRate.setText("Heart Rate");
        add(lblheartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        txtsysBP.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtsysBP.setEnabled(false);
        txtsysBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsysBPActionPerformed(evt);
            }
        });
        add(txtsysBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 110, -1));

        lblsysBP.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblsysBP.setText("Systolic Blood Pressure");
        add(lblsysBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        txtwt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtwt.setEnabled(false);
        txtwt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwtActionPerformed(evt);
            }
        });
        add(txtwt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));

        lblwt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblwt.setText("Weight in pounds");
        add(lblwt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("Get health record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void resetFields() {
        txtrespRate.setText("");
        txtheartRate.setText("");
        txtsysBP.setText("");
        txtwt.setText("");

    }
    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        String message = messageJTextField.getText();

        IncidentWorkRequest request = null;
        request = new IncidentWorkRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setPerson(p);

        int rrate = Integer.parseInt(txtrespRate.getText());
        int hrate = Integer.parseInt(txtheartRate.getText());
        int bp = Integer.parseInt(txtsysBP.getText());
        float wt = Float.parseFloat(txtwt.getText());

       
            VitalSign vs = p.getVitalSignHistory().addVitalSign();
            vs.setRespRate(rrate);
            vs.setHeartRate(hrate);
            vs.setBloodPressure(bp);
            vs.setWeight(wt);
            vs.getTimestamp();
        

        Organization org = null;
        for (Enterprise e : state.getEnterpriseDirectory().getEnterpriseList()) {
           //System.out.println("Enterprise is: " + e.getName());
            if (e instanceof HospitalEnterprise) {
               // System.out.println("Hospital Enterprise is: " + e.getName());
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    if (o instanceof ReceptionistOrganization && o.getZipCode().equals(messageJTextField.getText())) {
                        org = o;
                        break;

                    }

                }
            }
        }
        if (org != null) {
           // System.out.print("Sent req to" + org.getZipCode());
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            vworkrq.setStatus("Sent to Hospital" + org.getZipCode());
          //  System.out.println("Sent to Hospital" + org.getZipCode());
            JOptionPane.showMessageDialog(null, "Request made", "Add Success", JOptionPane.INFORMATION_MESSAGE);
            resetFields();

                    sms sms1 = new sms();
                        try {
                            sms1.sms1();
                        } catch (TwilioRestException ex) {
                            Logger.getLogger(RequestIncidentJPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
        } else {
            JOptionPane.showMessageDialog(this, "No zipcode match");
        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AmbulanceAdminWorkAreaJPanel dwjp = (AmbulanceAdminWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtrespRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrespRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrespRateActionPerformed

    private void txtheartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtheartRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtheartRateActionPerformed

    private void txtsysBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsysBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsysBPActionPerformed

    private void txtwtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwtActionPerformed

    private void messageJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageJTextFieldActionPerformed

    public void randomNumber() {

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int randomNumbers = (int) (Math.random() * 50 + 1);
        txtrespRate.setText(String.valueOf(randomNumbers));
        int randomNumbers1 = (int) (Math.random() * 50 + 1);
        txtheartRate.setText(String.valueOf(randomNumbers1));
        int randomNumbers2 = (int) (Math.random() * 50 + 1);
        txtsysBP.setText(String.valueOf(randomNumbers2));
        int randomNumbers3 = (int) (Math.random() * 50 + 1);
        txtwt.setText(String.valueOf(randomNumbers3));
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblheartRate;
    private javax.swing.JLabel lblrespRate;
    private javax.swing.JLabel lblsysBP;
    private javax.swing.JLabel lblwt;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextField txtheartRate;
    private javax.swing.JTextField txtrespRate;
    private javax.swing.JTextField txtsysBP;
    private javax.swing.JTextField txtwt;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
