/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReceptionistlRole;

import Business.Person.MedicalDocs;
import Business.Person.Person;
import Business.Person.VitalSign;
import Business.WorkQueue.RecToAsstdocWorkRequest;
import java.awt.CardLayout;
import java.text.MessageFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class ViewMedicalHistory extends javax.swing.JPanel {

    /**
     * Creates new form ViewMedicalHistory
     */
    private JPanel userProcessContainer;
    private RecToAsstdocWorkRequest request;
    private Person p;

    public ViewMedicalHistory(JPanel userProcessContainer, RecToAsstdocWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.p = request.getPerson();
        populateTable();
        populateImageTable();
    }

    private void populateLabel() {

        int selectedRow = jTable2.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }

        MedicalDocs request = (MedicalDocs) jTable2.getValueAt(selectedRow, 0);
        String url = request.getURL();
        jLabel1.setIcon(request.getImage(url));
    }
    
    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int rowCount = dtm.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        for (VitalSign vs : p.getVitalSignHistory().getVSHistory()) {
            Object[] row = new Object[2];
            row[0] = vs;
            row[1] = vs.getStatus(p, vs);
            dtm.addRow(row);
        }
    }

    private void populateImageTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        int rowCount = dtm.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        for (MedicalDocs vs : p.getDocList().getDocList()) {
            Object[] row = new Object[2];
            jTable2.getColumnModel().getColumn(1).setCellRenderer(jTable2.getDefaultRenderer(ImageIcon.class));
            row[0] = vs;
            String url = vs.getURL();
            row[1] = vs.getImage(url);
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblwt = new javax.swing.JLabel();
        TxtRespRate = new javax.swing.JTextField();
        txthrate = new javax.swing.JTextField();
        Txtbp = new javax.swing.JTextField();
        TxtWT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnViewDetails = new javax.swing.JButton();
        lblresprate = new javax.swing.JLabel();
        lblhrate = new javax.swing.JLabel();
        lblbp = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        lblwt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblwt.setText("Weight in pounds");

        TxtRespRate.setEditable(false);
        TxtRespRate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        txthrate.setEditable(false);
        txthrate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        Txtbp.setEditable(false);
        Txtbp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Txtbp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtbpActionPerformed(evt);
            }
        });

        TxtWT.setEditable(false);
        TxtWT.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Timestamp", "Normal/ Abnormal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnViewDetails.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        BtnViewDetails.setText("View Details");
        BtnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewDetailsActionPerformed(evt);
            }
        });

        lblresprate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblresprate.setText("Respiratory Rate");

        lblhrate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblhrate.setText("Heart Rate");

        lblbp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblbp.setText("Blood Pressure");

        backJButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("Generate Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("jLabel1");

        jButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton2.setText("View X-Ray");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblresprate)
                                    .addComponent(lblhrate)
                                    .addComponent(lblbp)
                                    .addComponent(lblwt))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txthrate)
                                    .addComponent(Txtbp)
                                    .addComponent(TxtWT)
                                    .addComponent(TxtRespRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addGap(45, 45, 45)
                                .addComponent(jButton1))
                            .addComponent(backJButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewDetails)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblresprate)
                            .addComponent(TxtRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblhrate))
                    .addComponent(txthrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbp)
                    .addComponent(Txtbp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblwt)
                    .addComponent(TxtWT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(backJButton)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtbpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtbpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtbpActionPerformed

    private void BtnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow >= 0) {
            VitalSign vs = (VitalSign) jTable1.getValueAt(selectedRow, 0);
            TxtRespRate.setText(String.valueOf(vs.getRespRate()));
            txthrate.setText(String.valueOf(vs.getHeartRate()));
            Txtbp.setText(String.valueOf(vs.getBloodPressure()));
            TxtWT.setText(String.valueOf(vs.getWeight()));
           // txtTimestamp.setText(vs.getTimestamp());

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row first !", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnViewDetailsActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Medical History");
        MessageFormat footer = new MessageFormat("Page(0,number,integer)");
        try {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
            System.out.println("vaishu");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot print");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        populateLabel();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnViewDetails;
    private javax.swing.JTextField TxtRespRate;
    private javax.swing.JTextField TxtWT;
    private javax.swing.JTextField Txtbp;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblbp;
    private javax.swing.JLabel lblhrate;
    private javax.swing.JLabel lblresprate;
    private javax.swing.JLabel lblwt;
    private javax.swing.JTextField txthrate;
    // End of variables declaration//GEN-END:variables
}
