/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CountryAdmin;

import Business.Country.Country;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dell
 */
public class CountryAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CountryAdminWorkArea
     */
    JPanel upc;
    EcoSystem system;
    UserAccount userAccount;
    Country country;

    public CountryAdminWorkArea(JPanel upc, EcoSystem business, UserAccount ua) {
        initComponents();
        this.upc = upc;
        this.system = business;
        userAccount = ua;
        for (Country c : system.getCountryList().getCountryDirectory()) {
            for (UserAccount u : c.getUserAccountDirectory().getUserAccountList()) {
                if (u.getUsername().equals(ua.getUsername())) {
                    country = c;

                }
            }

        }
        valueLabel.setText(country.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageStateJButton = new javax.swing.JButton();
        manageStateAdminJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        manageStateJButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        manageStateJButton.setText("Manage State");
        manageStateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStateJButtonActionPerformed(evt);
            }
        });

        manageStateAdminJButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        manageStateAdminJButton.setText("Manage State admin");
        manageStateAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStateAdminJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Country Admin Work Area");

        enterpriseLabel.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        enterpriseLabel.setText("Country");

        valueLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 12)); // NOI18N
        valueLabel.setText("<value>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(manageStateAdminJButton)
                            .addComponent(manageStateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel))
                .addGap(28, 28, 28)
                .addComponent(manageStateJButton)
                .addGap(18, 18, 18)
                .addComponent(manageStateAdminJButton)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageStateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStateJButtonActionPerformed
        ManageStateJPanel manageNetworkJPanel = new ManageStateJPanel(upc, country, userAccount);
        upc.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageStateJButtonActionPerformed

    private void manageStateAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStateAdminJButtonActionPerformed
        ManageStateAdminJPanel mcajp = new ManageStateAdminJPanel(upc, country, userAccount);
        upc.add("manageCountryAdminJPanel", mcajp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageStateAdminJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageStateAdminJButton;
    private javax.swing.JButton manageStateJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
